# Generated by Django 3.2.3 on 2021-08-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programas_instalados',
            old_name='ip_publica',
            new_name='pc',
        ),
        migrations.RemoveField(
            model_name='fcia',
            name='nombre_fcia',
        ),
        migrations.AddField(
            model_name='fcia',
            name='nombre_facia',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='nombre_farmacia'),
        ),
    ]
