# Generated by Django 3.2.3 on 2021-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0002_auto_20210818_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fcia',
            name='direccion',
        ),
        migrations.AddField(
            model_name='fcia',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activar'), (0, 'Desactivar')], default=1),
        ),
        migrations.AlterField(
            model_name='fcia',
            name='nro_cliente',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='Número de Cliente'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='id_localidad',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Localidad'),
        ),
    ]
